### ISSUE TITLE
Rendering Issues with Calendar Card

### ISSUE THREAD

**Issue by maumi** [shannonhochkins/ha-component-kit#231]
Calendar Card seems to have issues in rendering in some circumstances.
I try to organize my dashboard vertically, like 
`<Row>
  <Column>
  ...
  </Column>
  ...
</Row>`
When I do this with the weather Card and I set the column to FullWidth then this column jumps below my created columns and not right to my already existing columns. I can fix this by removing the fullWidth and then set eg `sm={12}` so the weather Card is not so small.
But with the calendarCard it is not that easy.
First of all, when I remove the fullWidth prop, then the card is shrinked in prod `npm run build` but not in dev `npm run dev` so they behave different.
Also when I set `disableColumns` this leads to a fullscreen in dev and a smaller view in prod.
And when I toggle `includeHeader ` in prod, the whole widget is gone and in dev the header is hidden as wished.
Also sometimes the calendar card seems to resize itself and make itself at first bigger than necessary (using more width than needed) and then gets smaller again to the wished size.
Hard to explain because it is mostly a re-rendering issue

**Comment by shannonhochkins** [comment]
Can you provide a replicatable issue showing what you're describing please? I'm not completely following as you're describing what looks like two separate issues

**Comment by maumi** [comment]
I try to split it in separate pieces starting with "Showing no content when header is hidden"
This shows up the calendar in dev but nothing in release build.

`import { ThemeProvider } from '@hakit/components';
import { HassConnect } from '@hakit/core';
import { CalendarCard } from '@hakit/components';
import { Column } from '@hakit/components';
import { Row } from '@hakit/components';

function App() {
  return (
    <>
      <HassConnect hassUrl={import.meta.env.VITE_HA_URL} hassToken={import.meta.env.VITE_HA_TOKEN}>
        <ThemeProvider includeThemeControls />
        <Row>
          <Column>
            <CalendarCard includeHeader={false} entities={['calendar.XXXX']} />
          </Column>
        </Row>
      </HassConnect>
    </>
  );
}

export default App;`

**Comment by shannonhochkins** [comment]
You'll need to provide a width on the columns. All cards have width set via a percentage, so if the parent is 0% width, then naturally, its children will too unless a pixel width is set.

You can add two columns in the Row, add your width (you can use the BP classes on the Row/Column as well to set the width to a percentage), and that should fix your problem

Unsure why you're seeing different behaviours in dev/prod, I can not replicate that with your provided code

**Comment by shannonhochkins** [comment]
For example, inside your Row, you'd have two columns, each with a class of `.xlg-6`, if you want a gap add the gap prop to the Row, then you'll most likely need to disable the columns on the card and use the Column if that's what you're after

**Comment by shannonhochkins** [comment]
https://shannonhochkins.github.io/ha-component-kit/?path=/docs/introduction-responsive-layouts-css-classes--docs

**Comment by maumi** [comment]
Okay thanks. It looks like I'm trying to round a circle, so trying to put responsive stuff into borders with too much column and rows.

But another real bug is when the size is defined and the view is set to 'dayGridDay' the view jumps back to the default view instead of the daily view at load.

Minimal example:
```
import { ThemeProvider } from '@hakit/components';
import { HassConnect } from '@hakit/core';
import { CalendarCard } from '@hakit/components';
import { Column } from '@hakit/components';

function App() {
  return (
    <>
      <HassConnect hassUrl={import.meta.env.VITE_HA_URL} hassToken={import.meta.env.VITE_HA_TOKEN}>
        <ThemeProvider includeThemeControls />
        <Column fullHeight>
          <CalendarCard sm={3} md={3} view='dayGridDay' entities={['calendar.XXXX', 'calendar.ani_maui']} />
        </Column>
      </HassConnect>
    </>
  );
}

export default App;

```

**Comment by shannonhochkins** [comment]
So you're saying the day view reverts when a size property is defined? I'm assuming this happens regardless of the size property however I'll take a look!

**Comment by maumi** [comment]
Exactly. When I remove the sm/md size prop, than it does not revert the view

**Comment by shannonhochkins** [comment]
That's odd! That most likely means the entire component is unmounting to reset its state, or there may be a separate bug updating the view internally based on the event data coming in, I'll check for you when I can and report back 😉 

Feel free to poke around if you have time, see if you can spot the bug! I'd say it's most likely a useEffect setting the view without first checking the input prop

**Comment by maumi** [comment]
I have looked into the code and it's because of this line and a width < 400.
Is there a good reason to switch back to the listView if width < 400?
[https://github.com/shannonhochkins/ha-component-kit/blob/5c969cef0f758ad1ae9eec6c756cfd6a26706b94/packages/components/src/Cards/CalendarCard/index.tsx#L514]

**Comment by shannonhochkins** [comment]
This logic was copied directly from the home assistant calendar card. However, it's possible they don't revert the view if a manual view was specified

**Comment by shannonhochkins** [comment]
I think we can safely change this so the automated view switch is only applied when the prop isn't provided, easy change!

**Comment by shannonhochkins** [comment]
This should be fixed now!

**Comment by maumi** [comment]
Not fixed for my case. When I look into your code, it only helps when the view is already set to the listView.
But in my case, the view is set to dayGridDay and the control is smaller than 400 it still changes the view.

**Comment by shannonhochkins** [comment]
The block to switch the view will only run when the `view` prop is undefined and the current view is not `listWeek`, I can see I did invert the check though, that block of code should ONLY run when the view prop is undefined, and I stupidly wrote `typeof view !== 'undefined'`....

Sorry @maumi - Will release another patch today

**Comment by shannonhochkins** [comment]
@maumi Please update both core/packages again `npm i @hakit/core@latest @hakit/components@latest`

Rather than introducing internal behavior that's not really known to the user by simply providing a default view, i've introduced two new props.

- `disableNarrow` - Will disable the class that's added to the card when the card is < 400px wide
- `disableAutoView` - Will disable the auto view switching based on card size

Let me know if this works for you!

**Comment by maumi** [comment]
Now it works with disableAutoView. Thanks
